CREATE TABLE Sheet1(USE_PassportDW VARCHAR(10),Column_2 VARCHAR(10),Column_3 VARCHAR(10),Column_4 VARCHAR(10),Column_5 VARCHAR(10),Column_6 VARCHAR(10),Column_7 VARCHAR(10));
INSERT INTO Sheet1 (USE_PassportDW,Column_2,Column_3,Column_4,Column_5,Column_6,Column_7) VALUES 
('GO','','','','','',''),
('/****** Object:  StoredProcedure [dbo].[spRpt_PinDebitReconciliationSummary]    Script Date: 8/26/2018 6:40:51 AM ******/','','','','','',''),
('SET ANSI_NULLS ON','','','','','',''),
('GO','','','','','',''),
('SET QUOTED_IDENTIFIER ON','','','','','',''),
('GO','','','','','',''),
('/***************************************************************************************','','','','','',''),
('Created By:       ','','','','','',''),
('Original Date: ','','','','','',''),
('Description:      Retrieves data for the SSRS report Corporate Pin Debit Reconciliation Summary','','','','','',''),
('Modification Log:','','','','','',''),
('Date                        Modified By:    FR/SWD #        Comment','','','','','',''),
('----------------------------------------------------------------------------------------','','','','','',''),
('****************************************************************************************/','','','','','',''),
('CREATE PROCEDURE [dbo].[spRpt_PinDebitReconciliationSummary](','','','','','',''),
('        @Date datetime','','','','','',''),
('        @AcquiringBank varchar(100)','','','','','',''),
('        @FrontEndType varchar(100))','','','','','',''),
('        WITH RECOMPILE /*  added "with recompile" to the PIN Debit Reconciliation Summary proc to improve sporadic report rendering issues.  This has resolved this same sporadic rendering issues on other SSRS reports in the past.        */','','','','','',''),
('AS','','','','','',''),
('        ','','','','','',''),
('declare @D1 int','','','','','',''),
('declare @D2 int','','','','','',''),
('declare @D3 int','','','','','',''),
('declare @D4 int','','','','','',''),
('declare @D5 int','','','','','',''),
('declare @D01 int','','','','','',''),
('declare @D02 int','','','','','',''),
('declare @D03 int','','','','','',''),
('declare @D04 int','','','','','',''),
('declare @D05 int','','','','','',''),
('declare @D06 int','','','','','',''),
('declare @D07 int','','','','','',''),
('declare @D08 int','','','','','',''),
('declare @D09 int','','','','','',''),
('declare @D10 int','','','','','',''),
('declare @D11 int','','','','','',''),
('set @D5 = convert(int',' convert(varchar(8)',' @Date',' 112))','','',''),
('set @D4 = convert(int',' convert(varchar(8)',' dateadd(d','- 1',' @Date)',' 112))',''),
('set @D3 = convert(int',' convert(varchar(8)',' dateadd(d','- 2',' @Date)',' 112))',''),
('set @D2 = convert(int',' convert(varchar(8)',' dateadd(d','- 3',' @Date)',' 112))',''),
('set @D1 = convert(int',' convert(varchar(8)',' dateadd(d','- 4',' @Date)',' 112))',''),
('set @D01 = convert(int',' convert(varchar(8)',' dateadd(d','- 5',' @Date)',' 112))',''),
('set @D02 = convert(int',' convert(varchar(8)',' dateadd(d','- 6',' @Date)',' 112))',''),
('set @D03 = convert(int',' convert(varchar(8)',' dateadd(d','- 7',' @Date)',' 112))',''),
('set @D04 = convert(int',' convert(varchar(8)',' dateadd(d','- 8',' @Date)',' 112))',''),
('set @D05 = convert(int',' convert(varchar(8)',' dateadd(d','- 9',' @Date)',' 112))',''),
('set @D06 = convert(int',' convert(varchar(8)',' dateadd(d','- 10',' @Date)',' 112))',''),
('set @D07 = convert(int',' convert(varchar(8)',' dateadd(d','- 11',' @Date)',' 112))',''),
('set @D08 = convert(int',' convert(varchar(8)',' dateadd(d','- 12',' @Date)',' 112))',''),
('set @D09 = convert(int',' convert(varchar(8)',' dateadd(d','- 13',' @Date)',' 112))',''),
('set @D10 = convert(int',' convert(varchar(8)',' dateadd(d','- 14',' @Date)',' 112))',''),
('set @D11 = convert(int',' convert(varchar(8)',' dateadd(d','- 15',' @Date)',' 112))',''),
('Begin','','','','','',''),
('        ','','','','','',''),
('SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED','','','','','',''),
('SET NOCOUNT ON','','','','','',''),
('select ','','','','','',''),
('Type = '1'','','','','','',''),
('ab.AcqBankName','','','','','',''),
('pt.guid','','','','','',''),
('pt.ID as ProviderTxnID','','','','','',''),
(''0' as PassportTxnID','','','','','',''),
('fe.ID','','','','','',''),
('Fe.Description as FrontEnd','','','','','',''),
('(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D11 then '-11'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D10 then '-10'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D09 then '-9'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D08 then '8'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D07 then '-7'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D06 then '-6'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D05 then '-5'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D04 then '-4'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D03 then '-3'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D02 then '-2'','','',''),
('          when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D01 then '-1'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D1 then '1'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D2 then '2'','','',''),
('          when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D3 then '3'','','',''),
('          when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D4 then '4'','','',''),
('          when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D5 then '5' else '' end) as DayType','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D11 then - PT.debitamount else 0 end) as C11D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D10 then - PT.debitamount else 0 end) as C10D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D09 then - PT.debitamount else 0 end) as C09D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D08 then - PT.debitamount else 0 end) as C08D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D07 then - PT.debitamount else 0 end) as C07D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D06 then - PT.debitamount else 0 end) as C06D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D05 then - PT.debitamount else 0 end) as C05D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D04 then - PT.debitamount else 0 end) as C04D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D03 then - PT.debitamount else 0 end) as C03D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D02 then - PT.debitamount else 0 end) as C02D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D01 then - PT.debitamount else 0 end) as C01D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D1 then - pt.debitamount else 0 end) as C1D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D2 then - pt.debitamount else 0 end) as C2D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D3 then - pt.debitamount else 0 end) as C3D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D4 then - pt.debitamount else 0 end) as C4D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D5 then - pt.debitamount else 0 end) as C5D','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D11 then PT.creditamount else 0 end) as C11C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D10 then PT.creditamount else 0 end) as C10C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D09 then PT.creditamount else 0 end) as C09C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D08 then PT.creditamount else 0 end) as C08C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D07 then PT.creditamount else 0 end) as C07C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D06 then PT.creditamount else 0 end) as C06C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D05 then PT.creditamount else 0 end) as C05C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D04 then PT.creditamount else 0 end) as C04C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D03 then PT.creditamount else 0 end) as C03C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D02 then PT.creditamount else 0 end) as C02C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D01 then PT.creditamount else 0 end) as C01C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D1 then pt.creditamount else 0 end) as C1C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D2 then pt.creditamount else 0 end) as C2C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D3 then pt.creditamount else 0 end) as C3C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D4 then pt.creditamount else 0 end) as C4C','','',''),
('sum(case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D5 then pt.creditamount else 0 end) as C5C','','',''),
('Into #tempproviderfunded','','','','','',''),
('from  dbo.ProviderTxn pt with(nolock)','','','','','',''),
('INNER JOIN dbo.ProviderTxnFiservEpoc ptfe with(nolock) ON pt.Id = ptfe.ProviderTxnId','','','','','',''),
('LEFT OUTER JOIN dbo.ProviderTxnFile ptf with(nolock) ON pt.ProviderTxnFileId = ptf.Id','','','','','',''),
('INNER JOIN dbo.fiservlogo fl with(nolock) on ptfe.acquirerlogo = fl.logo','','','','','',''),
('JOIN dbo.frontendtype fe with(nolock) on pt.hpsfrontendsubmitterid = fe.id','','','','','',''),
('JOIN AcqBank ab with(nolock) on fl.acquiringbankid = ab.acqbankID','','','','','',''),
('where ptf.Status = 2 and convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112))  between  @D11 and @D5 and ab.AcqBankID = @AcquiringBank and fe.ID = @FrontEndType','','',''),
('group by ','','','','','',''),
('ab.AcqBankName','','','','','',''),
('pt.guid','','','','','',''),
('PT.ID','','','','','',''),
('fe.ID','','','','','',''),
('Fe.Description','','','','','',''),
(' (case when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D11 then '-11'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D10 then '-10'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D09 then '-9'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D08 then '8'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D07 then '-7'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D06 then '-6'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D05 then '-5'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D04 then '-4'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D03 then '-3'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D02 then '-2'','','',''),
('          when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D01 then '-1'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D1 then '1'','','',''),
('      when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D2 then '2'','','',''),
('          when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D3 then '3'','','',''),
('          when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D4 then '4'','','',''),
('          when convert(int',' convert(varchar(8)',' pt.DateAdded-1',' 112)) = @D5 then '5' else '' end)','','',''),
('        ','','','','','',''),
('select ','','','','','',''),
('Type = '2'','','','','','',''),
('ab.AcqBankName','','','','','',''),
(''0' as ProviderTxnID','','','','','',''),
('pt.id as PassportTxnID','','','','','',''),
('fe.ID','','','','','',''),
('Fe.Description as FrontEnd','','','','','',''),
('sott.ServiceOptionTxnTypeID','','','','','',''),
('(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D11 then '-11'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D10 then '-10'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D09 then '-9'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D08 then '-8'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D07 then '-7'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D06 then '-6'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D05 then '-5'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D04 then '-4'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D03 then '-3'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D02 then '-2'','','',''),
('          when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D01 then '-1'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D1 then '1'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D2 then '2'','','',''),
('          when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D3 then '3'','','',''),
('          when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D4 then '4'','','',''),
('          when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D5 then '5' else '' end) as DayType','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D11 then PT.Amount else 0 end) as C11','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D10 then PT.Amount else 0 end) as C10','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D09 then PT.Amount else 0 end) as C09','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D08 then PT.Amount else 0 end) as C08','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D07 then PT.Amount else 0 end) as C07','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D06 then PT.Amount else 0 end) as C06','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D05 then PT.Amount else 0 end) as C05','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D04 then PT.Amount else 0 end) as C04','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D03 then PT.Amount else 0 end) as C03','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D02 then PT.Amount else 0 end) as C02','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D01 then PT.Amount else 0 end) as C01','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D1 then PT.Amount else 0 end) as C1','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D2 then PT.Amount else 0 end) as C2','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D3 then PT.Amount else 0 end) as C3','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D4 then PT.Amount else 0 end) as C4','','',''),
('sum(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D5 then PT.Amount else 0 end) as C5','','',''),
('Into #tempPassportSettledtoMerchant','','','','','',''),
('from dbo.PassportTxn pt with(nolock)','','','','','',''),
('JOIN dbo.PassportSubmission ps with(nolock) on pt.PassportSubmissionId = ps.ID','','','','','',''),
('JOIN dbo.TxnHeader th with(nolock) on pt.txnuuid = th.txnuuid','','','','','',''),
('JOIN dbo.frontendtype fe with(nolock) on ps.submitterid = fe.id','','','','','',''),
('JOIN AcqBank ab with(nolock) on pt.AcqBankId = ab.AcqBankID','','','','','',''),
('JOIN serviceoptiontxntype sott with(nolock) on pt.serviceoptiontxntypeid = sott.serviceoptiontxntypeid','','','','','',''),
('where ps.LoadProcessStatus = 2 and pt.debitconsolidatorid = '2' and convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) between  @D11 and @D5 and ab.AcqBankID = @AcquiringBank and fe.ID = @FrontEndType','','',''),
('group by ab.AcqBankName','','','','','',''),
('PT.ID','','','','','',''),
('fe.ID','','','','','',''),
('Fe.Description','','','','','',''),
('sott.ServiceOptionTxnTypeID','','','','','',''),
('(case when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D11 then '-11'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D10 then '-10'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D09 then '-9'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D08 then '-8'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D07 then '-7'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D06 then '-6'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D05 then '-5'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D04 then '-4'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D03 then '-3'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D02 then '-2'','','',''),
('          when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D01 then '-1'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D1 then '1'','','',''),
('      when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D2 then '2'','','',''),
('          when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D3 then '3'','','',''),
('          when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D4 then '4'','','',''),
('          when convert(int',' convert(varchar(8)',' th.businessdateutcid',' 112)) = @D5 then '5'  else '' end)','','',''),
('select ','','','','','',''),
('Type = '3'','','','','','',''),
('ab.AcqBankName','','','','','',''),
('TM.PassportTxnID','','','','','',''),
('TM.ProviderTxnID',' ','','','','',''),
('fe.ID','','','','','',''),
('Fe.Description as FrontEnd','','','','','',''),
('sott.ServiceOptionTxnTypeID','','','','','',''),
('pt.amount','','','','','',''),
('Into #tempPassportSettledandPaidtoMerchant','','','','','',''),
('from #tempproviderfunded pf','','','','','',''),
('JOIN TxnMatch tm with(nolock) on pf.ProviderTxnID = tm.providertxnid','','','','','',''),
('JOIN dbo.PassportTxn pt with(nolock) on tm.passporttxnid  = pt.ID','','','','','',''),
('JOIN dbo.PassportSubmission ps with(nolock) ON pt.PassportSubmissionId = ps.ID','','','','','',''),
('JOIN dbo.frontendtype fe with(nolock) on ps.submitterid = fe.id','','','','','',''),
('JOIN AcqBank ab with(nolock) on pt.AcqBankId = ab.AcqBankID','','','','','',''),
('JOIN serviceoptiontxntype sott with(nolock) on pt.serviceoptiontxntypeid = sott.serviceoptiontxntypeid','','','','','',''),
('Where pt.debitconsolidatorid = '2' and tm.ProviderTxnId not in (Select providertxnid from LateMatchedProviderTxnNotification with(nolock))','','','','','',''),
('and tm.PassportTxnId not in (Select PassportTxnID from LateMatchedPassportTxnNotification with(nolock))','','','','','',''),
('Select Type',' AcqBankName',' FrontEnd',' DayType',' providertxnid',' passporttxnid','  '),
('sum(isnull(a.C05D','0) + isnull(a.C05C','0)) as Provider05','','','',''),
('sum(isnull(a.C04D','0) + isnull(a.C04C','0)) as Provider04','','','',''),
('sum(isnull(a.C03D','0) + isnull(a.C03C','0)) as Provider03','','','',''),
('sum(isnull(a.C02D','0) + isnull(a.C02C','0)) as Provider02','','','',''),
('sum(isnull(a.C01D','0) + isnull(a.C01C','0)) as Provider01','','','',''),
('sum(isnull(a.C1D','0) + isnull(a.C1C','0)) as Provider1',' ','','',''),
('sum(isnull(a.C2D','0) + isnull(a.C2C','0)) as Provider2',' ','','',''),
('sum(isnull(a.C3D','0) + isnull(a.C3C','0)) as Provider3',' ','','',''),
('sum(isnull(a.C4D','0) + isnull(a.C4C','0)) as Provider4','','','',''),
('sum(isnull(a.C5C','0) + isnull(a.C5D','0)) as Provider5','','','',''),
('Into #tempProviderList','','','','','',''),
('from #tempproviderfunded a','','','','','',''),
('group by Type','AcqBankName',' FrontEnd',' DayType','providertxnid',' passporttxnid',''),
('Select Type','AcqBankName',' FrontEnd',' DayType',' providertxnid',' passporttxnid',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C11 else b.C11 end) as Passport11','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C10 else b.C10 end) as Passport10','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C09 else b.C09 end) as Passport09','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C08 else b.C08 end) as Passport08','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C07 else b.C07 end) as Passport07','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C06 else b.C06 end) as Passport06','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C05 else b.C05 end) as Passport05','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C04 else b.C04 end) as Passport04','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C03 else b.C03 end) as Passport03','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C02 else b.C02 end) as Passport02','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C01 else b.C01 end) as Passport01','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C1 else b.C1 end) as Passport1','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C2 else b.C2 end) as Passport2','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C3 else b.C3 end) as Passport3','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C4 else b.C4 end) as Passport4','','','','','',''),
('sum(case when b.serviceoptiontxntypeid = 20 then -b.C5 else b.C5 end) as Passport5','','','','','',''),
('Into #tempPassportList','','','','','',''),
('from #tempPassportSettledtoMerchant b','','','','','',''),
('group by Type',' AcqBankName',' FrontEnd',' DayType',' providertxnid',' passporttxnid',''),
('Select Type',' AcqBankName',' FrontEnd','  ProviderTxnID',' PassportTxnID',' sum(case when serviceoptiontxntypeid = 20 then -amount else amount end) as MatchedAmount',''),
('Into #tempMatchList','','','','','',''),
('from #tempPassportSettledandPaidtoMerchant c','','','','','',''),
('group by Type',' AcqBankName',' FrontEnd','  providertxnid',' passporttxnid','',''),
('select ','','','','','',''),
('coalesce(a.AcqBankName',' b.AcqBankName) as AcqBankName','','','','',''),
('coalesce(a.FrontEnd',' b.FrontEnd) as FrontEnd','','','','',''),
('sum(Provider05) as Provider05',' ','','','','',''),
('sum(Provider04) as Provider04',' ','','','','',''),
('sum(Provider03) as Provider03',' ','','','','',''),
('sum(Provider02) as Provider02',' ','','','','',''),
('sum(Provider01) as Provider01',' ','','','','',''),
('sum(Provider1) as Provider1',' ','','','','',''),
('sum(Provider2) as Provider2',' ','','','','',''),
('sum(Provider3) as Provider3',' ','','','','',''),
('sum(Provider4) as Provider4',' ','','','','',''),
('sum(Provider5) as Provider5',' ','','','','',''),
('sum(Passport02) as Passport02',' ','','','','',''),
('sum(Passport01) as Passport01',' ','','','','',''),
('sum(Passport1) as Passport1','  ','','','','',''),
('sum(Passport2) as Passport2','  ','','','','',''),
('sum(Passport3) as Passport3','  ','','','','',''),
('sum(Passport4) as Passport4 ',' ','','','','',''),
('sum(Passport5) as Passport5','','','','','',''),
('Into #tempProviderPassportList','','','','','',''),
('from #tempProviderList a','','','','','',''),
('FULL OUTER JOIN #tempPassportList b on (a.acqbankname = b.acqbankname and a.frontend = b.frontend and a.daytype = b.daytype and a.type = b.type)','','','','','',''),
('group by ','','','','','',''),
('coalesce(a.AcqBankName',' b.AcqBankName)','','','','',''),
('coalesce(a.FrontEnd',' b.FrontEnd)','','','','',''),
('Select','','','','','',''),
('a.Type','','','','','',''),
('a.AcqBankName','','','','','',''),
('a.FrontEnd','','','','','',''),
('Case when b.type = 1 and b.daytype = 5 and c.type = 2 and c.daytype = 5 then MatchedAmount else '0' end as Date1','','','','','',''),
('Case when b.type = 1 and b.daytype = 5 and c.type = 2 and c.daytype = 4 then MatchedAmount else '0' end as Date2','','','','','',''),
('Case when b.type = 1 and b.daytype = 5 and c.type = 2 and c.daytype = 3 then MatchedAmount else '0' end as Date3','','','','','',''),
('Case when b.type = 1 and b.daytype = 5 and c.type = 2 and c.daytype = 2 then MatchedAmount else '0' end as Date4','','','','','',''),
('Case when b.type = 1 and b.daytype = 5 and c.type = 2 and c.daytype = 1 then MatchedAmount else '0' end as Date5','','','','','',''),
('Case when b.type = 1 and b.daytype = 5 and c.type = 2 and c.daytype = -1 then MatchedAmount else '0' end as DateBefore1','','','','','',''),
('Case when b.type = 1 and b.daytype = 5 and c.type = 2 and c.daytype = -2 then MatchedAmount else '0' end as DateBefore2','','','','','',''),
('Case when b.type = 1 and b.daytype = 5 and c.type = 2 and c.daytype not in (1','2','3','4','5) then MatchedAmount else '0' end as PreviouslyMatched5','',''),
('-----------------------------------------------------------------------------------------------------------------','','','','','',''),
('Case when b.type = 1 and b.daytype = 4 and c.type = 2 and c.daytype = 5 then MatchedAmount else '0' end as Date6','','','','','',''),
('Case when b.type = 1 and b.daytype = 4 and c.type = 2 and c.daytype = 4 then MatchedAmount else '0' end as Date7','','','','','',''),
('Case when b.type = 1 and b.daytype = 4 and c.type = 2 and c.daytype = 3 then MatchedAmount else '0' end as Date8','','','','','',''),
('Case when b.type = 1 and b.daytype = 4 and c.type = 2 and c.daytype = 2 then MatchedAmount else '0' end as Date9','','','','','',''),
('Case when b.type = 1 and b.daytype = 4 and c.type = 2 and c.daytype = 1 then MatchedAmount else '0' end as Date10','','','','','',''),
('Case when b.type = 1 and b.daytype = 4 and c.type = 2 and c.daytype = -1 then MatchedAmount else '0' end as DateBefore3','','','','','',''),
('Case when b.type = 1 and b.daytype = 4 and c.type = 2 and c.daytype = -2 then MatchedAmount else '0' end as DateBefore4','','','','','',''),
('Case when b.type = 1 and b.daytype = 4 and c.type = 2 and c.daytype not in (1','2','3','4','5) then MatchedAmount else '0' end as PreviouslyMatched4','',''),
('------------------------------------------------------------------------------------------------------------------','','','','','',''),
('Case when b.type = 1 and b.daytype = 3 and c.type = 2 and c.daytype = 5 then MatchedAmount else '0' end as Date11','','','','','',''),
('Case when b.type = 1 and b.daytype = 3 and c.type = 2 and c.daytype = 4 then MatchedAmount else '0' end as Date12','','','','','',''),
('Case when b.type = 1 and b.daytype = 3 and c.type = 2 and c.daytype = 3 then MatchedAmount else '0' end as Date13','','','','','',''),
('Case when b.type = 1 and b.daytype = 3 and c.type = 2 and c.daytype = 2 then MatchedAmount else '0' end as Date14','','','','','',''),
('Case when b.type = 1 and b.daytype = 3 and c.type = 2 and c.daytype = 1 then MatchedAmount else '0' end as Date15','','','','','',''),
('Case when b.type = 1 and b.daytype = 3 and c.type = 2 and c.daytype = -1 then MatchedAmount else '0' end as DateBefore5','','','','','',''),
('Case when b.type = 1 and b.daytype = 3 and c.type = 2 and c.daytype = -2 then MatchedAmount else '0' end as DateBefore6','','','','','',''),
('Case when b.type = 1 and b.daytype = 3 and c.type = 2 and c.daytype not in (1','2','3','4','5) then MatchedAmount else '0' end as PreviouslyMatched3','',''),
('-----------------------------------------------------------------------------------------------------------------','','','','','',''),
('Case when b.type = 1 and b.daytype = 2 and c.type = 2 and c.daytype = 5 then MatchedAmount else '0' end as Date16','','','','','',''),
('Case when b.type = 1 and b.daytype = 2 and c.type = 2 and c.daytype = 4 then MatchedAmount else '0' end as Date17','','','','','',''),
('Case when b.type = 1 and b.daytype = 2 and c.type = 2 and c.daytype = 3 then MatchedAmount else '0' end as Date18','','','','','',''),
('Case when b.type = 1 and b.daytype = 2 and c.type = 2 and c.daytype = 2 then MatchedAmount else '0' end as Date19','','','','','',''),
('Case when b.type = 1 and b.daytype = 2 and c.type = 2 and c.daytype = 1 then MatchedAmount else '0' end as Date20','','','','','',''),
('Case when b.type = 1 and b.daytype = 2 and c.type = 2 and c.daytype = -1 then MatchedAmount else '0' end as DateBefore7','','','','','',''),
('Case when b.type = 1 and b.daytype = 2 and c.type = 2 and c.daytype = -2 then MatchedAmount else '0' end as DateBefore8','','','','','',''),
('Case when b.type = 1 and b.daytype = 2 and c.type = 2 and c.daytype not in (1','2','3','4','5) then MatchedAmount else '0' end as PreviouslyMatched2','',''),
('-----------------------------------------------------------------------------------------------------------------','','','','','',''),
('Case when b.type = 1 and b.daytype = 1 and c.type = 2 and c.daytype = 5 then MatchedAmount else '0' end as Date21','','','','','',''),
('Case when b.type = 1 and b.daytype = 1 and c.type = 2 and c.daytype = 4 then MatchedAmount else '0' end as Date22','','','','','',''),
('Case when b.type = 1 and b.daytype = 1 and c.type = 2 and c.daytype = 3 then MatchedAmount else '0' end as Date23','','','','','',''),
('Case when b.type = 1 and b.daytype = 1 and c.type = 2 and c.daytype = 2 then MatchedAmount else '0' end as Date24','','','','','',''),
('Case when b.type = 1 and b.daytype = 1 and c.type = 2 and c.daytype = 1 then MatchedAmount else '0' end as Date25','','','','','',''),
('Case when b.type = 1 and b.daytype = 1 and c.type = 2 and c.daytype = -1 then MatchedAmount else '0' end as DateBefore9','','','','','',''),
('Case when b.type = 1 and b.daytype = 1 and c.type = 2 and c.daytype = -2 then MatchedAmount else '0' end as DateBefore10','','','','','',''),
('Case when b.type = 1 and b.daytype = 1 and c.type = 2 and c.daytype not in (1','2','3','4','5) then MatchedAmount else '0' end as PreviouslyMatched','',''),
('-----------------------------------------------------------------------------------------------------------------','','','','','',''),
('Case when b.type = 1 and b.daytype = -1 and c.type = 2 and c.daytype = 5 then MatchedAmount else '0' end as Date26','','','','','',''),
('Case when b.type = 1 and b.daytype = -1 and c.type = 2 and c.daytype = 4 then MatchedAmount else '0' end as Date27','','','','','',''),
('Case when b.type = 1 and b.daytype = -1 and c.type = 2 and c.daytype = 3 then MatchedAmount else '0' end as Date28','','','','','',''),
('Case when b.type = 1 and b.daytype = -1 and c.type = 2 and c.daytype = 2 then MatchedAmount else '0' end as Date29','','','','','',''),
('Case when b.type = 1 and b.daytype = -1 and c.type = 2 and c.daytype = 1 then MatchedAmount else '0' end as Date30','','','','','',''),
('Case when b.type = 1 and b.daytype = -1 and c.type = 2 and c.daytype = -1 then MatchedAmount else '0' end as DateBefore11','','','','','',''),
('Case when b.type = 1 and b.daytype = -1 and c.type = 2 and c.daytype = -2 then MatchedAmount else '0' end as DateBefore12','','','','','',''),
('Case when b.type = 1 and b.daytype = -1 and c.type = 2 and c.daytype not in (1','2','3','4','5) then MatchedAmount else '0' end as PreviouslyMatched01','',''),
('---------------------------------------------------------------------------------------------------------------------------------------------','','','','','',''),
('Case when b.type = 1 and b.daytype = -2 and c.type = 2 and c.daytype = 5 then MatchedAmount else '0' end as Date31','','','','','',''),
('Case when b.type = 1 and b.daytype = -2 and c.type = 2 and c.daytype = 4 then MatchedAmount else '0' end as Date32','','','','','',''),
('Case when b.type = 1 and b.daytype = -2 and c.type = 2 and c.daytype = 3 then MatchedAmount else '0' end as Date33','','','','','',''),
('Case when b.type = 1 and b.daytype = -2 and c.type = 2 and c.daytype = 2 then MatchedAmount else '0' end as Date34','','','','','',''),
('Case when b.type = 1 and b.daytype = -2 and c.type = 2 and c.daytype = 1 then MatchedAmount else '0' end as Date35','','','','','',''),
('Case when b.type = 1 and b.daytype = -2 and c.type = 2 and c.daytype = -1 then MatchedAmount else '0' end as DateBefore13','','','','','',''),
('Case when b.type = 1 and b.daytype = -2 and c.type = 2 and c.daytype = -2 then MatchedAmount else '0' end as DateBefore14','','','','','',''),
('Case when b.type = 1 and b.daytype = -2 and c.type = 2 and c.daytype not in (1','2','3','4','5) then MatchedAmount else '0' end as PreviouslyMatched02','',''),
('----------------------------------------------------------------------------------------------------------------------------------------------','','','','','',''),
('Case when b.type = 1 and b.daytype = -3 and c.type = 2 and c.daytype = 5 then MatchedAmount else '0' end as Date36','','','','','',''),
('Case when b.type = 1 and b.daytype = -3 and c.type = 2 and c.daytype = 4 then MatchedAmount else '0' end as Date37','','','','','',''),
('Case when b.type = 1 and b.daytype = -3 and c.type = 2 and c.daytype = 3 then MatchedAmount else '0' end as Date38','','','','','',''),
('Case when b.type = 1 and b.daytype = -3 and c.type = 2 and c.daytype = 2 then MatchedAmount else '0' end as Date39','','','','','',''),
('Case when b.type = 1 and b.daytype = -3 and c.type = 2 and c.daytype = 1 then MatchedAmount else '0' end as Date40','','','','','',''),
('Case when b.type = 1 and b.daytype = -3 and c.type = 2 and c.daytype = -1 then MatchedAmount else '0' end as DateBefore15','','','','','',''),
('Case when b.type = 1 and b.daytype = -3 and c.type = 2 and c.daytype = -2 then MatchedAmount else '0' end as DateBefore16','','','','','',''),
('Case when b.type = 1 and b.daytype = -3 and c.type = 2 and c.daytype not in (1','2','3','4','5) then MatchedAmount else '0' end as PreviouslyMatched03','',''),
('-----------------------------------------------------------------------------------------------------------------------------------------------','','','','','',''),
('Case when b.type = 1 and b.daytype = -4 and c.type = 2 and c.daytype = 5 then MatchedAmount else '0' end as Date41','','','','','',''),
('Case when b.type = 1 and b.daytype = -4 and c.type = 2 and c.daytype = 4 then MatchedAmount else '0' end as Date42','','','','','',''),
('Case when b.type = 1 and b.daytype = -4 and c.type = 2 and c.daytype = 3 then MatchedAmount else '0' end as Date43','','','','','',''),
('Case when b.type = 1 and b.daytype = -4 and c.type = 2 and c.daytype = 2 then MatchedAmount else '0' end as Date44','','','','','',''),
('Case when b.type = 1 and b.daytype = -4 and c.type = 2 and c.daytype = 1 then MatchedAmount else '0' end as Date45','','','','','',''),
('Case when b.type = 1 and b.daytype = -4 and c.type = 2 and c.daytype = -1 then MatchedAmount else '0' end as DateBefore17','','','','','',''),
('Case when b.type = 1 and b.daytype = -4 and c.type = 2 and c.daytype = -2 then MatchedAmount else '0' end as DateBefore18','','','','','',''),
('Case when b.type = 1 and b.daytype = -4 and c.type = 2 and c.daytype not in (1','2','3','4','5) then MatchedAmount else '0' end as PreviouslyMatched04','',''),
('-----------------------------------------------------------------------------------------------------------------------------------------------','','','','','',''),
('Case when b.type = 1 and b.daytype = -5 and c.type = 2 and c.daytype = 5 then MatchedAmount else '0' end as Date46','','','','','',''),
('Case when b.type = 1 and b.daytype = -5 and c.type = 2 and c.daytype = 4 then MatchedAmount else '0' end as Date47','','','','','',''),
('Case when b.type = 1 and b.daytype = -5 and c.type = 2 and c.daytype = 3 then MatchedAmount else '0' end as Date48','','','','','',''),
('Case when b.type = 1 and b.daytype = -5 and c.type = 2 and c.daytype = 2 then MatchedAmount else '0' end as Date49','','','','','',''),
('Case when b.type = 1 and b.daytype = -5 and c.type = 2 and c.daytype = 1 then MatchedAmount else '0' end as Date50','','','','','',''),
('Case when b.type = 1 and b.daytype = -5 and c.type = 2 and c.daytype = -1 then MatchedAmount else '0' end as DateBefore19','','','','','',''),
('Case when b.type = 1 and b.daytype = -5 and c.type = 2 and c.daytype = -2 then MatchedAmount else '0' end as DateBefore20','','','','','',''),
('Case when b.type = 1 and b.daytype = -5 and c.type = 2 and c.daytype not in (1','2','3','4','5) then MatchedAmount else '0' end as PreviouslyMatched05','',''),
('Into  #tempMatched','','','','','',''),
('from #tempMatchList a with(nolock)','','','','','',''),
('Join #tempProviderList b with(nolock) on a.providertxnid =  b.providertxnid','','','','','',''),
('join #tempPassportList c with(nolock) on a.passporttxnid = c.passporttxnid','','','','','',''),
('select ','','','','','',''),
('coalesce(a.AcqBankName','b.AcqBankName) as AcqBankName','','','','',''),
('coalesce(a.FrontEnd','b.FrontEnd) as FrontEnd','','','','',''),
('Provider05','','','','','',''),
('Provider04','','','','','',''),
('Provider03','','','','','',''),
('Provider02','','','','','',''),
('Provider01','','','','','',''),
('Provider1 as Provider1','','','','','',''),
('Provider2 as Provider2','','','','','',''),
('Provider3 as Provider3','','','','','',''),
('Provider4 as Provider4','','','','','',''),
('Provider5 as Provider5','','','','','',''),
('Passport02','','','','','',''),
('Passport01','','','','','',''),
('Passport1 as Passport1','','','','','',''),
('Passport2 as Passport2','','','','','',''),
('Passport3 as Passport3','','','','','',''),
('Passport4 as Passport4','','','','','',''),
('Passport5 as Passport5','','','','','',''),
('sum(Date1) as Date1','','','','','',''),
('sum(Date2) as Date2','','','','','',''),
('sum(Date3) as Date3','','','','','',''),
('sum(Date4) as Date4','','','','','',''),
('sum(Date5) as Date5','','','','','',''),
('sum(Datebefore1) as Datebefore1','','','','','',''),
('sum(Datebefore2) as Datebefore2','','','','','',''),
('sum(Date6) as Date6','','','','','',''),
('sum(Date7) as Date7','','','','','',''),
('sum(Date8) as Date8','','','','','',''),
('sum(Date9) as Date9','','','','','',''),
('sum(Date10) as Date10','','','','','',''),
('sum(Datebefore3) as Datebefore3','','','','','',''),
('sum(Datebefore4) as Datebefore4','','','','','',''),
('sum(Date11) as Date11','','','','','',''),
('sum(Date12) as Date12','','','','','',''),
('sum(Date13) as Date13','','','','','',''),
('sum(Date14) as Date14','','','','','',''),
('sum(Date15) as Date15','','','','','',''),
('sum(Datebefore5) as Datebefore5','','','','','',''),
('sum(Datebefore6) as Datebefore6','','','','','',''),
('sum(Date16) as Date16','','','','','',''),
('sum(Date17) as Date17','','','','','',''),
('sum(Date18) as Date18','','','','','',''),
('sum(Date19) as Date19','','','','','',''),
('sum(Date20) as Date20','','','','','',''),
('sum(Datebefore7) as Datebefore7','','','','','',''),
('sum(Datebefore8) as Datebefore8','','','','','',''),
('sum(Date21) as Date21','','','','','',''),
('sum(Date22) as Date22','','','','','',''),
('sum(Date23) as Date23','','','','','',''),
('sum(Date24) as Date24','','','','','',''),
('sum(Date25) as Date25','','','','','',''),
('sum(Datebefore9) as Datebefore9','','','','','',''),
('sum(Datebefore10) as Datebefore10','','','','','',''),
('sum(Date26) as Date26','','','','','',''),
('sum(Date27) as Date27','','','','','',''),
('sum(Date28) as Date28','','','','','',''),
('sum(Date29) as Date29','','','','','',''),
('sum(Date30) as Date30','','','','','',''),
('sum(Datebefore11) as Datebefore11','','','','','',''),
('sum(Datebefore12) as Datebefore12','','','','','',''),
('sum(Date31) as Date31','','','','','',''),
('sum(Date32) as Date32','','','','','',''),
('sum(Date33) as Date33','','','','','',''),
('sum(Date34) as Date34','','','','','',''),
('sum(Date35) as Date35','','','','','',''),
('sum(Datebefore13) as Datebefore13','','','','','',''),
('sum(Datebefore14) as Datebefore14','','','','','',''),
('sum(Date36) as Date36','','','','','',''),
('sum(Date37) as Date37','','','','','',''),
('sum(Date38) as Date38','','','','','',''),
('sum(Date39) as Date39','','','','','',''),
('sum(Date40) as Date40','','','','','',''),
('sum(Datebefore15) as Datebefore15','','','','','',''),
('sum(Datebefore16) as Datebefore16','','','','','',''),
('sum(Date41) as Date41','','','','','',''),
('sum(Date42) as Date42','','','','','',''),
('sum(Date43) as Date43','','','','','',''),
('sum(Date44) as Date44','','','','','',''),
('sum(Date45) as Date45','','','','','',''),
('sum(Datebefore17) as Datebefore17','','','','','',''),
('sum(Datebefore18) as Datebefore18','','','','','',''),
('sum(Date46) as Date46','','','','','',''),
('sum(Date47) as Date47','','','','','',''),
('sum(Date48) as Date48','','','','','',''),
('sum(Date49) as Date49','','','','','',''),
('sum(Date50) as Date50','','','','','',''),
('sum(Datebefore19) as Datebefore19','','','','','',''),
('sum(Datebefore20) as Datebefore20','','','','','',''),
('sum(PreviouslyMatched5) as PreviouslyMatched5','','','','','',''),
('sum(PreviouslyMatched4) as PreviouslyMatched4','','','','','',''),
('sum(PreviouslyMatched3) as PreviouslyMatched3','','','','','',''),
('sum(PreviouslyMatched2) as PreviouslyMatched2','','','','','',''),
('sum(PreviouslyMatched) as PreviouslyMatched','','','','','',''),
('sum(PreviouslyMatched01) as PreviouslyMatched01','','','','','',''),
('sum(PreviouslyMatched02) as PreviouslyMatched02','','','','','',''),
('sum(PreviouslyMatched03) as PreviouslyMatched03','','','','','',''),
('sum(PreviouslyMatched04) as PreviouslyMatched04','','','','','',''),
('sum(PreviouslyMatched05) as PreviouslyMatched05','','','','','',''),
('from #tempProviderPassportList a','','','','','',''),
('FULL OUTER JOIN #tempMatched b on a.acqbankname = b.acqbankname and a.frontend =b.frontend','','','','','',''),
('group by coalesce(a.AcqBankName','b.AcqBankName)','','','','',''),
('coalesce(a.FrontEnd','b.FrontEnd)','','','','',''),
('Provider05','','','','','',''),
('Provider04','','','','','',''),
('Provider03','','','','','',''),
('Provider02','','','','','',''),
('Provider01','','','','','',''),
('Provider1','','','','','',''),
('Provider2','','','','','',''),
('Provider3','','','','','',''),
('Provider4','','','','','',''),
('Provider5','','','','','',''),
('Passport02','','','','','',''),
('Passport01','','','','','',''),
('Passport1','','','','','',''),
('Passport2','','','','','',''),
('Passport3','','','','','',''),
('Passport4','','','','','',''),
('Passport5','','','','','',''),
('END ','','','','','',''),
('GO','','','','','','');